--SELECT AU.AUTHOR_ID, AU.AUTHOR_NAME, BO.CATEGORY, SUM(BS.SALES)
--FROM AUTHOR AU
--JOIN BOOK BO ON AU.AUTHOR_ID = BO.AUTHOR_ID
--JOIN BOOK_SALES BS ON BO.BOOK_ID = BS.BOOK_ID
--WHERE BS.SALES_DATE BETWEEN TO_DATE('20220101','YYYYMMDD') AND TO_DATE('20220131','YYYYMMDD')
--GROUP BY AU.AUTHOR_ID, AU.AUTHOR_NAME, BO.CATEGORY

SELECT AU.AUTHOR_ID, AU.AUTHOR_NAME, BOOK_SUM.CATEGORY,BOOK_SUM.SUM AS TOTAL_SALES
FROM AUTHOR AU
JOIN
(SELECT BO.AUTHOR_ID,BO.CATEGORY, SUM(BO.PRICE * BS.SALES) AS SUM
FROM BOOK BO
JOIN BOOK_SALES BS ON BO.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE BETWEEN TO_DATE('20220101','YYYYMMDD') AND TO_DATE('20220131','YYYYMMDD')
GROUP BY BO.AUTHOR_ID,BO.CATEGORY) BOOK_SUM
ON BOOK_SUM.AUTHOR_ID = AU.AUTHOR_ID
ORDER BY AU.AUTHOR_ID ASC, BOOK_SUM.CATEGORY DESC


