SELECT 
    CRC.CAR_ID, 
    CRC.CAR_TYPE, 
    TRUNC(CRC.DAILY_FEE * (1 - CRCD.DISCOUNT_RATE / 100) * 30) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR CRC
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCD 
    ON CRC.CAR_TYPE = CRCD.CAR_TYPE AND CRCD.DURATION_TYPE = '30일 이상'
WHERE 
    CRC.CAR_TYPE IN ('세단', 'SUV')
    AND CRC.CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE (START_DATE <= DATE '2022-11-30' AND END_DATE >= DATE '2022-11-01')
    )
    AND CRC.DAILY_FEE * (1 - CRCD.DISCOUNT_RATE / 100) * 30 BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC, CRC.CAR_TYPE ASC, CRC.CAR_ID DESC;
