-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS,ROUND(RV.SCORE,2) AS SCORE
FROM REST_INFO RI, 
(SELECT REST_ID AS REST_ID,AVG(NVL(REVIEW_SCORE,0)) AS SCORE FROM REST_REVIEW 
 GROUP BY REST_ID) RV
WHERE RI.REST_ID = RV.REST_ID
AND RI.ADDRESS LIKE '서울%'
ORDER BY RV.SCORE DESC, RI.FAVORITES DESC;



