SELECT YEAR(SAL.SALES_DATE) AS YEAR,
       MONTH(SAL.SALES_DATE) AS MONTH,
       USR.GENDER, COUNT(DISTINCT(USR.USER_ID)) AS USERS
FROM USER_INFO USR
JOIN ONLINE_SALE SAL
ON USR.USER_ID = SAL.USER_ID
WHERE USR.GENDER IS NOT NULL
GROUP BY YEAR(SAL.SALES_DATE), MONTH(SAL.SALES_DATE), USR.GENDER
ORDER BY YEAR ASC ,MONTH ASC ,GENDER ASC