-- YEAR MONTH GENDER USERS
SELECT TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'YYYY')) AS YEAR,
TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'MM')) AS MONTH, USR.GENDER, COUNT(DISTINCT(USR.USER_ID)) AS USERS
FROM USER_INFO USR, ONLINE_SALE SAL
WHERE USR.USER_ID = SAL.USER_ID
AND USR.GENDER IS NOT NULL
GROUP BY TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'YYYY')), TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'MM')), USR.GENDER
ORDER BY TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'YYYY')),TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'MM')),USR.GENDER