-- 코드를 입력하세요
-- YEAR MONTH PURCHASED_USERS PUCHASED_RATIO
SELECT TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'YYYY')) AS YEAR, 
       TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'MM')) AS MONTH,
       COUNT(DISTINCT(SAL.USER_ID)) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT(SAL.USER_ID))/TOTAL.TOTAL,1) AS PUCHASED_RATIO
FROM USER_INFO USR, ONLINE_SALE SAL,
(
    SELECT TO_CHAR(JOINED,'YYYY') AS DT,
           COUNT(USER_ID) AS TOTAL
    FROM USER_INFO
    WHERE TO_CHAR(JOINED,'YYYY') = '2021'
    GROUP BY TO_CHAR(JOINED,'YYYY')
) TOTAL
WHERE USR.USER_ID = SAL.USER_ID
AND TOTAL.DT = TO_CHAR(USR.JOINED,'YYYY')
GROUP BY TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'YYYY')), 
         TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'MM')), TOTAL.TOTAL
ORDER BY TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'YYYY')), 
         TO_NUMBER(TO_CHAR(SAL.SALES_DATE,'MM'))


