WITH RECURSIVE CT AS(
SELECT ID, 1 AS GENERATION FROM ECOLI_DATA WHERE PARENT_ID IS NULL
UNION ALL
    SELECT
        A.ID, GENERATION + 1 AS GENERATION
    FROM
        ECOLI_DATA A LEFT JOIN CT B ON A.PARENT_ID = B.ID
    WHERE
        A.PARENT_ID = B.ID)
SELECT COUNT(*) AS COUNT,GENERATION FROM CT
WHERE NOT EXISTS(SELECT 1 FROM ECOLI_DATA WHERE PARENT_ID = CT.ID)
GROUP BY GENERATION;