-- 코드를 입력하세요
SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME,SUM(PRO.PRICE*ORD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT PRO
JOIN FOOD_ORDER ORD
ON PRO.PRODUCT_ID = ORD.PRODUCT_ID
WHERE ORD.PRODUCE_DATE BETWEEN TO_DATE('2022-05-01','YYYY-MM-DD') AND TO_DATE('2022-05-31','YYYY-MM-DD')
GROUP BY PRO.PRODUCT_ID, PRO.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRO.PRODUCT_ID ASC;