-- 코드를 입력하세요
SELECT T.MEMBER_NAME, T.REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d')
FROM
(SELECT M.MEMBER_NAME,R.REVIEW_TEXT,R.REVIEW_DATE, 
DENSE_RANK() OVER (ORDER BY TEMP.CNT DESC) AS RK
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
JOIN (SELECT RR.MEMBER_ID AS MEMID, COUNT(*) AS CNT
FROM REST_REVIEW RR
GROUP BY RR.MEMBER_ID) TEMP
ON R.MEMBER_ID = TEMP.MEMID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT) T
WHERE T.RK = 1;
