--MEMBER_NAME / REVIEW_TEXT / REVIEW_DATE
--리뷰를 가장 많이 작성한 회원의 리뷰 조회
SELECT TT.MEMBER_NAME, TT.REVIEW_TEXT, TO_CHAR(TT.REVIEW_DATE,'YYYY-MM-DD')
FROM
(SELECT MEM.MEMBER_NAME, RV.REVIEW_TEXT,RV.REVIEW_DATE,
RANK() OVER(ORDER BY RNK.CNT DESC) AS RK
FROM MEMBER_PROFILE MEM, REST_REVIEW RV,
(SELECT MEMBER_ID, COUNT(*) AS CNT
 FROM REST_REVIEW
 GROUP BY MEMBER_ID
 ORDER BY COUNT(*) DESC) RNK
WHERE MEM.MEMBER_ID = RV.MEMBER_ID
AND RV.MEMBER_ID = RNK.MEMBER_ID) TT
WHERE TT.RK = 1
ORDER BY TT.REVIEW_DATE ASC,TT.REVIEW_TEXT ASC;

