-- 코드를 입력하세요


--RANK(), DENSE_RANK(), ROW_NUMBER() 차이점 정리 (ORACLE,MYSQL)

SELECT T.MEMBER_NAME, T.REVIEW_TEXT,TO_CHAR(REVIEW_DATE,'YYYY-MM-DD')
FROM
(SELECT M.MEMBER_NAME,R.REVIEW_TEXT,R.REVIEW_DATE, 
DENSE_RANK() OVER (ORDER BY TEMP.CNT DESC) AS RK
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
JOIN (SELECT RR.MEMBER_ID AS MEMID, COUNT(*) AS CNT
FROM REST_REVIEW RR
GROUP BY RR.MEMBER_ID) TEMP
ON R.MEMBER_ID = TEMP.MEMID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT) T
WHERE T.RK = 1;


