SELECT T.ID,T.FISH_NAME,T.LENGTH FROM
(SELECT INF.ID AS ID, NM.FISH_NAME AS FISH_NAME, INF.LENGTH AS LENGTH, 
RANK() OVER(PARTITION BY NM.FISH_NAME ORDER BY INF.LENGTH DESC) AS RK
FROM FISH_INFO INF
JOIN FISH_NAME_INFO NM
ON INF.FISH_TYPE = NM.FISH_TYPE) T
WHERE T.RK = 1
ORDER BY T.ID ASC;

