-- 코드를 작성해주세요
SELECT TT.ID, TT.FISH_NAME, TT.LENGTH FROM
(SELECT FI.ID AS ID, FN.FISH_NAME AS FISH_NAME, FI.LENGTH AS LENGTH,RANK() OVER(PARTITION BY FI.FISH_TYPE ORDER BY FI.LENGTH DESC) AS RN
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FN
ON FI.FISH_TYPE = FN.FISH_TYPE) TT
WHERE TT.RN=1
ORDER BY TT.ID

