-- 코드를 작성해주세요

SELECT MAX(G.TOTAL_SCORE) AS SCORE,HE.EMP_NO, HE.EMP_NAME,HE.POSITION,HE.EMAIL 
FROM
(SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
FROM HR_GRADE
GROUP BY EMP_NO) G
JOIN HR_EMPLOYEES HE 
ON G.EMP_NO = HE.EMP_NO
GROUP BY HE.EMP_NO, HE.EMP_NAME,HE.POSITION,HE.EMAIL
ORDER BY MAX(G.TOTAL_SCORE) DESC
LIMIT 1;

