-- 코드를 작성해주세요

SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, ROUND(AVG(HE.SAL),0) as AVG_SAL
FROM HR_DEPARTMENT HD
INNER JOIN HR_EMPLOYEES HE
ON HD.DEPT_ID = HE.DEPT_ID
GROUP BY HD.DEPT_ID, HD.DEPT_NAME_EN
order by AVG_SAL DESC