-- 코드를 입력하세요
--SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
--FROM FOOD_PRODUCT
--WHERE CATEGORY IN ('과자','국','김치','식용유')
--ORDER BY PRICE DESC;
SELECT RANK.CATEGORY as CATEGORY, RANK.PRICE AS MAX_PRICE,PRODUCT_NAME AS PRODUCT_NAME
FROM
(SELECT CATEGORY,PRICE,PRODUCT_NAME, ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) as rank
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자','국','김치','식용유')) RANK
WHERE RANK.rank = 1
ORDER BY RANK.PRICE DESC;